version: '3'
services:

  laravelmap:
    image: mattrayner/lamp:latest-1404-php5
    container_name: laravelmap
    volumes:
      - /app/mapProject:/app
      - mysql:/var/lib/mysql
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mapapp
    restart: on-failure

volumes:
  app:
  mysql:

networks:
  mapapp:
